### ISSUE TITLE
Implement OpenGraph + clean up meta data

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/release-blog#40]
We don't have any opengraph data set for social sharing
- [x] Remove IE9 html5 shim
- [x] Add meta description
- [x] Remove old Chrome frame meta tag
- [x] Add sharing illustration image meta + image
- [x] Add OpenGraph metadata
- [x] Add Twitter metadata
- [x] Add Google share metadata

**Comment by pascalchevrel** [comment]
Should be good but let's keep this one open until https://bugzilla.mozilla.org/show_bug.cgi?id=1357118 is fixed because some of the metadata is currently not picked up by the Twitter and Facebook metadata validator because I think of the current missing https certificate.

**Comment by pascalchevrel** [comment]
This is working now
